# -*- coding: utf-8 -*-
"""IBP_class.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kM6k84N9yiMgNzUrZebfyPAdydgGpGrh
"""

print('We are learning python')

# variable
x = 9
x = x * 3
print(x)

9 != 8

1+1 == 2

y = 2.3
print(y)

type(y)

string = "Ammar"
print(string)

list_one = [12, 'ammar', 2.3]
print(list_one)

print(list_one[0])

list_one[0] = 13
list_one

tuple_one = (1,'Ammar', 3)

Dict = {"Gender": "Male", "CNIC": "1234"}


# 4 Dict / 5 keyvalue pairs
print(5 +1)

print( 5 / 3)

print( 5 // 3)

print(5 ** 3)

import math
from math import sqrt

sqrt(125)

print(125 ** (1/3))

1 / 3

x = x % 3
 x += 125 %3

x  = "hello world"
  print('' in x)

print( 5 & 3)

int(input(" Insert value: "))

age = int(input("Enter number: "))
if age < 12:
  print('Cannot smoke')
else:
  print('Who are you')

stock_price = float(input('Enter Value: '))
if stock_price > 20:
  print(stock_price + 20)
else:
  print(stock_price-20)

# Write a program to subtract age from 10 if its less than 100
# write a program  to calculate your profit from 20% of the cost

for i in range(1,10):
  print(i, "is five times equal to ", i*5)

for i in range(13):
  print(i, "is five times equal to ", i*5)

i = 0
while i <= 5:
  if (i == 4):
    break

i = 0
while i < 5:
  if i == 4:
    break
  print(i)
  i = i + 1

def int_inc(x,r,y,m):
  if x == r*0.7:
    return y*1.01
  elif m == y*1.04:
    return r*1.01

def tax_calc(tx,tr,x):
  if tx == tr*x:
    print('You are an honest tax payer')
  else:
    print('You are dishonest')

tax_calc(12,0.1,120)

def g_t(x):
  if x == 'Male':
    return 0
  elif x == "Transgender":
    return 2
  elif x == "Female":
    return 1
  else:
    print(" you are an alien")

g_t('Male')

g_t('Female')

g_t('Spirit Animal')

pd.DataFrame({'monkeydict':pd.Series(monkeydict),'pigdict':pd.Series(pigdict)})